//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database_lib.EntityDbDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class simple_mailEntities : DbContext
    {
        public simple_mailEntities()
            : base("name=simple_mailEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<message_users> message_users { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<messages_view> messages_view { get; set; }
    }
}
