//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database_lib.EntityDbDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class message_users
    {
        public int msg_id { get; set; }
        public int user_id { get; set; }
        public int state { get; set; }
    
        public virtual message message { get; set; }
        public virtual user user { get; set; }
    }
}
