//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database_lib.EntityDbDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public message()
        {
            this.message_users = new HashSet<message_users>();
        }
    
        public int msg_id { get; set; }
        public int author_id { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
        public System.DateTime pub_date { get; set; }
        public int state { get; set; }
    
        public virtual ICollection<message_users> message_users { get; set; }
    }
}
