//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database_lib.EntityDbDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages_view
    {
        public int messages_msg_id { get; set; }
        public string messages_subject { get; set; }
        public string messages_text { get; set; }
        public System.DateTime messages_pub_date { get; set; }
        public int messages_state { get; set; }
        public int author_id { get; set; }
        public string author_first_name { get; set; }
        public string author_email { get; set; }
        public int author_state { get; set; }
        public int recipient_user_id { get; set; }
        public string recipient_first_name { get; set; }
        public string recipient_email { get; set; }
        public int recipient_state { get; set; }
        public int messages_recipient_msg_state { get; set; }
    }
}
